---
- name: Launch a Drupal single instance CloudFormation stack
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Launch a CloudFormation stack
    cloudformation: >
      stack_name="8nZ19OGumK_Drupal"
      state=present
      region=us-east-1
      disable_rollback=true
      template=Drupal_Single_Instance.template
    args:
      template_parameters:
        KeyName: 8nZ19OGumK_DrupalKey
        SiteName: "HDS Drupal Website"
    register: stack
  - name: Show stack outputs
    debug: msg="HDS stack outputs are {{stack.stack_outputs}}"
